const modes=[
  {id:"instruction",shortcut:"1",label:"INSTRUCTIE",icon:"!",headline:"Let op",detail:"Stop je oefening. Pen neer. Kijk en luister.",color:"#d56f22",soft:"#fff1e6"},
  {id:"solo",shortcut:"2",label:"ZELF",icon:"●",headline:"Stil en zelfstandig",detail:"Je werkt volledig zelfstandig en in stilte.",color:"#2876a0",soft:"#e8f4fa"},
  {id:"teacher",shortcut:"3",label:"ZELF + HAND",icon:"✋",headline:"Zelfstandig met leerkrachthulp",detail:"Herlees de oefening en bekijk de theorie. Nog vast? Steek je hand op.",color:"#765ca9",soft:"#f1edfa"},
  {id:"neighbour",shortcut:"4",label:"BUURHULP",icon:"↔",headline:"Zacht overleggen",detail:"Je mag zacht overleggen met je buur. Leg uit; schrijf niet over.",color:"#318b70",soft:"#e8f6f1"}
];

const root=document.documentElement,picker=document.querySelector("#mode-picker");
const els={icon:document.querySelector("#mode-icon"),label:document.querySelector("#mode-label"),headline:document.querySelector("#mode-headline"),detail:document.querySelector("#mode-detail")};
let active=modes.find(m=>m.id===localStorage.getItem("werkstand"))||modes[0],pipWindow=null;

function renderButtons(){picker.innerHTML=modes.map(m=>`<button type="button" class="mode-button ${m.id===active.id?"is-active":""}" data-mode="${m.id}" style="--mode:${m.color};--mode-soft:${m.soft}" aria-pressed="${m.id===active.id}"><span class="shortcut">${m.shortcut}</span><span class="button-icon" aria-hidden="true">${m.icon}</span><span class="button-text"><strong>${m.label}</strong><small>${m.headline}</small></span></button>`).join("")}
function paintCompact(target,mode){target.document.documentElement.style.setProperty("--mode",mode.color);target.document.querySelector("#pip-icon").textContent=mode.icon;target.document.querySelector("#pip-label").textContent=mode.label;target.document.querySelector("#pip-headline").textContent=mode.headline;target.document.querySelector("#pip-detail").textContent=mode.detail}
function prepareCompact(target){target.document.title="Werkstand";target.document.body.innerHTML=`<main class="pip-card"><div id="pip-icon" class="pip-icon"></div><div><p class="pip-kicker">HUIDIGE WERKSTAND</p><h1 id="pip-label"></h1><h2 id="pip-headline"></h2><p id="pip-detail"></p></div></main>`;const style=target.document.createElement("style");style.textContent=`:root{--mode:#d56f22}*{box-sizing:border-box}body{margin:0;background:#f3f7f9;color:#17384d;font-family:Arial,sans-serif}.pip-card{min-height:100vh;border:10px solid var(--mode);padding:22px;display:grid;grid-template-columns:82px 1fr;gap:18px;align-items:center;background:white}.pip-icon{width:82px;height:82px;border-radius:50%;display:grid;place-items:center;background:var(--mode);color:white;font-size:54px;font-weight:900}.pip-kicker{margin:0 0 4px;color:var(--mode);font-size:11px;font-weight:800;letter-spacing:.14em}h1{margin:0;font-size:clamp(30px,10vw,58px);line-height:1}h2{margin:7px 0 0;color:var(--mode);font-size:clamp(17px,5vw,27px)}#pip-detail{margin:8px 0 0;font-size:clamp(13px,3.5vw,18px);line-height:1.35;color:#324955}@media(max-width:410px){.pip-card{grid-template-columns:1fr;text-align:center}.pip-icon{margin:auto}}`;target.document.head.appendChild(style)}
function selectMode(id){active=modes.find(m=>m.id===id)||active;root.style.setProperty("--active",active.color);root.style.setProperty("--soft",active.soft);els.icon.textContent=active.icon;els.label.textContent=active.label;els.headline.textContent=active.headline;els.detail.textContent=active.detail;localStorage.setItem("werkstand",active.id);renderButtons();if(pipWindow&&!pipWindow.closed)paintCompact(pipWindow,active)}
async function openPip(){if(pipWindow&&!pipWindow.closed){pipWindow.focus();paintCompact(pipWindow,active);return}pipWindow=window.documentPictureInPicture?await window.documentPictureInPicture.requestWindow({width:520,height:310}):window.open("","werkstand-compact","popup=yes,width=520,height=310");if(!pipWindow)return;prepareCompact(pipWindow);paintCompact(pipWindow,active);pipWindow.addEventListener("pagehide",()=>pipWindow=null)}

picker.addEventListener("click",e=>{const button=e.target.closest("[data-mode]");if(button)selectMode(button.dataset.mode)});
document.querySelector("#pip-button").addEventListener("click",openPip);
document.querySelector("#fullscreen-button").addEventListener("click",()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen());
window.addEventListener("keydown",e=>{const mode=modes.find(m=>m.shortcut===e.key);if(mode)selectMode(mode.id);if(e.key.toLowerCase()==="f")document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen()});
selectMode(active.id);
